---
- name: Create user
  user:
    name: "{{ username }}"
    state: present
    groups: sudo
    append: yes
    password: "{{ password }}"
    password_expire_max: 1
    password_expire_min: 1

- name: Copy SSH key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ public_key }}"
