---
  name: PR
  
  on:
    push:
      branches:
        - '*'
        - '*/*'
        - '**'
        - '!main'

  env:
    TF_EXTRA_ARGS: '-var="username=test-gh" -var="packages_list=[\"git\"]" -var="remote_commands=[\"echo test-gh\"]" -var="public_key_name=test-gh" -var="digitalocean_token=123" -var="droplet_size=s-1vcpu-1gb" -var="droplet_size=s-1vcpu-1gb" -var="droplet_tags=[\"ubuntu\"]" -var="droplet_project_name=test-gh"'

  jobs:    
    pr:
      uses: obervinov/_templates/.github/workflows/pr.yaml@v2.0.2

    terraform:
      uses: obervinov/_templates/.github/workflows/terraform.yaml@v2.0.2
