name: Check terraform code

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'

jobs:
  terraform-check:
    uses: obervinov/_templates/.github/workflows/verify.terraform.yml@release/v1.0.5
